update {table_name} set offer_date = regexp_replace(trim(offer_date), '[\.\/]', '-', 'g') where regexp_matches(offer_date, '[\.\/]') = true;
update {table_name} set offer_date = strptime(offer_date, '%d-%m-%Y') where regexp_matches(offer_date, '^\d{2}-.');
update {table_name} set web_price = NULL where regexp_matches(web_price, '\D');
update {table_name} set sap_price = NULL where regexp_matches(sap_price, '\D');
update {table_name} set offer_date = strptime(array_extract(regexp_split_to_array(full_path, '\\'), 12), '%Y%m%d') where regexp_matches(offer_date, '^[345789]') or offer_date is null;
update {table_name} set unique_urs = string_to_array(regexp_replace(unique_urs,'[\[\]]', '', 'g'), ',');
update {table_name} set commercialdev = string_to_array(regexp_replace(commercialdev,'[\[\]]', '', 'g'), ',');
update {table_name} set jointdev = string_to_array(regexp_replace(jointdev,'[\[\]]', '', 'g'), ',');
update {table_name} set offer_id = regexp_replace(trim(offer_id), '[\n\t\W]', '', 'g')[:7] where regexp_matches(offer_id, '[\n\t\W]');
update {table_name} set offer_id = NULL where len(offer_id) < 6 or regexp_matches(offer_id, '[a-zA-Z]');
alter table {table_name} alter column offer_date set data type date;
alter table {table_name} alter column web_price set data type double;
alter table {table_name} alter column sap_price set data type double;
alter table {table_name} alter column unique_urs set data type int[];
alter table {table_name} alter column commercialdev set data type int[];
alter table {table_name} alter column jointdev set data type int[];
alter table {table_name} alter column offer_id set data type int;
